AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FuzzyWuzzy
Globals:
    Function:
        Timeout: 3
        Runtime: python3.7

Resources:
    FuzzyWuzzyLambdaLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: fuzzywuzzy
            Description: FuzzyWuzzy Lambda Layer
            ContentUri: ./layer.zip
            CompatibleRuntimes:
              - python3.7
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain